### ISSUE TITLE
Knowing when there is an error

### ISSUE THREAD

**Issue by Stono** [Fried-Chicken/ghost-static-site-generator#10]
At the moment, I simply eyeball the output looking for errors.

It'd be nice to add a flag such as `--fail-on-error` which would stop the process and exit non-zero if there were any scrape errors rather than the current default in https://github.com/Fried-Chicken/ghost-static-site-generator/blob/master/src/helpers/crawlPageHelper/crawlPageHelper.js#L19 which is just to write to stdout.

It'd also be nice if that file output the `wget` command that failed in the log too, so you can run it manually and try and work out what's up.

**Comment by Fried-Chicken** [comment]
Version `0.1.0-7` now has this flag
