### ISSUE TITLE
Javascript error on blog page

### ISSUE THREAD

**Issue by Stono** [Fried-Chicken/ghost-static-site-generator#11]
If you go to https://karlstoney.com/2018/02/23/nginx-ingress-modsecurity-and-secchatops/ you'll see:

<img width="581" alt="screenshot 2019-01-05 at 23 39 28" src="https://user-images.githubusercontent.com/1486729/50730348-30c1d080-1143-11e9-8322-081abe16b70a.png">

**Comment by Fried-Chicken** [comment]
Hmmm, I'm not sure why you have that. I have the same fitVid implementation and it works for me. Maybe it is conflicting with another library you use.

**Comment by Stono** [comment]
Hey; Not ignoring this btw just having a really busy couple of days!
Will get back to you on this and the others ASAP

**Comment by Fried-Chicken** [comment]
Hey @Stono 

Can I close this issue?

**Comment by Fried-Chicken** [comment]
HI @Stono

I'm closing this ticket, please re-open if it's still valid for you.

Thanks

@Fried-Chicken
