### ISSUE TITLE
--url option does not take in account subdirs

### ISSUE THREAD

**Issue by RobertoMalatesta** [Fried-Chicken/ghost-static-site-generator#12]
Hi and thanks for this nice utility!

I've noticed that if I want to publish the static site into a subdirectory, assets, content and public are loaded from web server root.

I would expect that issuing this command:
`gssg --url "https://www.samplehostname.com/staticsite_dir01/" --dest staticsite_dir01`
everything would be stored into and **referenced from** staticsite_dir01 ready to be dropped inside
the public_html of the web server.

Does an option for this exist/is in consideration?

Thanks in advance,

--R

**Comment by Fried-Chicken** [comment]
Hey @RobertoMalatesta 

This is something I didn't consider. I'll take a look later and implement something for you.

😃

**Comment by RobertoMalatesta** [comment]
Thanks @Fried-Chicken .
A loop searching for things like
`src=` 
gets all root-relative resources and external-referencing links, like code.jquery.com and static.ghost.org that could be cleansed and locally stored. 

See:

`find . -type f -iname "*" | xargs grep src\=`

shows:

![image](https://user-images.githubusercontent.com/11835025/51190522-b16e9280-18e2-11e9-8f50-cd78d8226e00.png)



After the extraction a process fixing them should be enough to implement it.

Please feel free to ask for help if you need it.

Rob

**Comment by RobertoMalatesta** [comment]
Maybe URLs as well should be fixed:
![image](https://user-images.githubusercontent.com/11835025/51191169-24c4d400-18e4-11e9-940f-d9804a1932b7.png)

**Comment by Fried-Chicken** [comment]
Hey @RobertoMalatesta 

I've had a go as implementing a `--subDir` flag.

Can you try this version `npm i -g ghost-static-site-generator@0.1.5-1` with this command ` gssg --dest a-random-dir --subDir a-random-dir --preview` and let me know if it works.

Thanks

@Fried-Chicken

**Comment by RobertoMalatesta** [comment]
Just a quick answer @Fried-Chicken : 
It works smoothly with : 
`gssg --url "https://www.theTargetSite.com" --dest staticDir --subDir staticDir`

I will do some tests and submit a more comprehensive feedback.

--Rob

PS: I never used ghost before. Your brilliant tool sold me it :+1:

**Comment by Fried-Chicken** [comment]
@RobertoMalatesta That's great to hear! I really like Ghost, I think their team did an amazing job building something that is simple to use and fast!

Let me know if you have any other issues :)

**Comment by Fried-Chicken** [comment]
@RobertoMalatesta Published new version and closed this ticket. Please re-open if there is any other issues regarding this issue.

Thanks
@Fried-Chicken

**Comment by RobertoMalatesta** [comment]
experimenting on themes.
(finding a bunch of weird things, but not dependent on your tool)
--R

**Comment by Fried-Chicken** [comment]
Oh, what kind of weird things are you experiencing? Sounds interesting.

**Comment by RobertoMalatesta** [comment]
scripts not correctly wonking on one theme, a bunch of ttf not correctly mirrored on another.
(incoming screenshot on edit of this message, starting up the machine)

**Comment by RobertoMalatesta** [comment]
1) 
On bleak Ghost theme [https://github.com/zutrinken/bleak](https://github.com/zutrinken/bleak)
the javascript menu breaks with javascript error:
![image](https://user-images.githubusercontent.com/11835025/51417350-e1859200-1b7d-11e9-966b-11be45ea5269.png)
... not dependng on your util but on some script, the top right menu is irresponsive.
Burger on the right:
![image](https://user-images.githubusercontent.com/11835025/51417467-72f50400-1b7e-11e9-9a8f-a38e735709b2.png)

it should pop up like this:
![image](https://user-images.githubusercontent.com/11835025/51417498-99b33a80-1b7e-11e9-90c7-c7001a303373.png)

http-server does not show any missing request.
Not  a great ish since I will take it out anyway and integrate with my OpenUI5 top menu... but just playing with it.

**Comment by Fried-Chicken** [comment]
@RobertoMalatesta Have you added any code or code injection?

**Comment by RobertoMalatesta** [comment]
2) font issue: let me change theme and remirror and I'll be back...

**Comment by RobertoMalatesta** [comment]
> @RobertoMalatesta Have you added any code or code injection?
zilch for now.
Only applied the theme.

**Comment by Fried-Chicken** [comment]
Can you host it somewhere where I can have a look?

**Comment by RobertoMalatesta** [comment]
Sure. follow me on twitter at @exedraos and I'll send you a link.

**Comment by RobertoMalatesta** [comment]
Random MAN ??
