### ISSUE TITLE
Relative paths is replacing regex in js

### ISSUE THREAD

**Issue by Fried-Chicken** [Fried-Chicken/ghost-static-site-generator#13]
Relative paths is replacing regex in js

**Comment by RobertoMalatesta** [comment]
Hi @Fried-Chicken (hope you slept well!)
a big bonus of relative paths is that you could have absolute portability and entirely drop the `--url` path option.
Ping me here if you need tests.
--R

**Comment by Fried-Chicken** [comment]
Hi @RobertoMalatesta 

I've made all the paths relative for src files now. Please try `v1.0.0-0` with the command `gssg --domain http://localhost:2368 --url http://www.yoursite.com --subDir your-dir` at this time, we still need the `--url` flag as we have to use it to differentiate between some edge case.

However you should find the site is more portable now.

Regarding the font issue, maybe if the new version has an issue can you rehost so I can check it out.

**Comment by RobertoMalatesta** [comment]
(just saw it... I did not abandon you, but Github did not show me the update otification for the message).
lllooooking ....

**Comment by RobertoMalatesta** [comment]
Getting closer:
now if you do `gssg --url "http://127.0.0.1:8080"  --dest static` and then you cd into static and serve from there everything seems working OK.
I noticed that `gssg --url ""  --dest static` appends a "/" to all resources.Maybe you have to take it out as well.
The JS seems to work now.
Uploading a sample in the directory you know.

--R

**Comment by Fried-Chicken** [comment]
@RobertoMalatesta Did you use the `--subDir your-dir` flag? You need to use this to make base links work.

Try this `gssg --domain "http://127.0.0.1:8080" --url "http://www.yoursite.com" --dest static --subDir estatic`

**Comment by RobertoMalatesta** [comment]
taking out the url altogether and adopting relative paths you won't need subDir but only a --dest where to put a completely relocatable mirror.

**Comment by Fried-Chicken** [comment]
@RobertoMalatesta I did try taking out the url altogether, but then you mess with all the SEO canonical links and other links that should be hardcoded. That's why I've opted for this solution.

There is two problems I currently see
1: Favicons are linking relative to the path, when it should be absolute from the base
2: Some links return you to `/estatic` rather than `/estatic/` which breaks the images.

I will need to investigate this and see how it can be handled.

**Comment by RobertoMalatesta** [comment]
What about serving everything that is `http://<yourghostaddr>:2368` relatively with the dest as root (without hardwiring it) stripping out all `http://<yourghostaddr>:2368` ?

**Comment by RobertoMalatesta** [comment]
This way the only hardcoded links are those pointing outside the file served by ghost.
Everything is inside is mirrored and independent.

**Comment by Fried-Chicken** [comment]
The problem is when the search engines crawl the site, they need to pick up `<link rel="canonical" href="http://<yourghostaddr>:2368/estatic/" />` it has to be absolute `http://<yourghostaddr>:2368/estatic/` and not relative.

**Comment by RobertoMalatesta** [comment]
I don't see the issue, unless you need it for wget.
Engines will crawl it in a relative fashion thus reconstructing the position.

**Comment by Fried-Chicken** [comment]
They will, but it's not recommended to use relative paths for canonical links.

**Comment by RobertoMalatesta** [comment]
I just read the paragraph on canonical links.
It makes sense but it leads to a less moveable content.
Solution of canonicald should be a different utility (not this) that gives a list of exact links and when you move the content reproduces an updated list of canonical links.

**Comment by RobertoMalatesta** [comment]
If you realy need them.

**Comment by Fried-Chicken** [comment]
Let's me see, maybe it's not too much of an issue to have them relative.

**Comment by Fried-Chicken** [comment]
Hey @RobertoMalatesta

I've updated the tool now to accept a `--ignore-absolute-paths` rule. Please try
`gssg --domain "http://127.0.0.1:8080" --url "http://www.yoursite.com" --dest estatic --subDir estatic --ignore-absolute-paths`
 and see if it works for you.

Thanks

@Fried-Chicken

**Comment by RobertoMalatesta** [comment]
` gssg  --domain "http://localhost:2368"   --url "http://localhost:8080" --dest estatic --subDir estatic --ignore-absolute-paths`

Gives this error:

```
Fetching: http://localhost:2368/sitemap.xsl
Downloading...
--- error:
Error: Invalid URI "estatic"
    at Request.init (/home/nodeuser/.nvm/versions/node/v10.13.0/lib/node_modules/node-wget/node_modules/request/request.js:274:31)
    at new Request (/home/nodeuser/.nvm/versions/node/v10.13.0/lib/node_modules/node-wget/node_modules/request/request.js:128:8)
    at request (/home/nodeuser/.nvm/versions/node/v10.13.0/lib/node_modules/node-wget/node_modules/request/index.js:53:10)
    at wget (/home/nodeuser/.nvm/versions/node/v10.13.0/lib/node_modules/node-wget/wget.js:46:4)
    at Object.<anonymous> (/home/nodeuser/.nvm/versions/node/v10.13.0/lib/node_modules/node-wget/cli.js:75:7)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: EISDIR: illegal operation on a directory, open './estatic'
ERROR: null
Using Command: wget -q --recursive --timestamping --page-requisites --no-parent --no-host-directories --restrict-file-name=unix --trust-server-names --directory-prefix estatic http://localhost:2368/sitemap.xsl
Fetching: http://localhost:2368/sitemap.xml
Downloading...
--- error:
Error: Invalid URI "estatic"
    at Request.init (/home/nodeuser/.nvm/versions/node/v10.13.0/lib/node_modules/node-wget/node_modules/request/request.js:274:31)
    at new Request (/home/nodeuser/.nvm/versions/node/v10.13.0/lib/node_modules/node-wget/node_modules/request/request.js:128:8)
    at request (/home/nodeuser/.nvm/versions/node/v10.13.0/lib/node_modules/node-wget/node_modules/request/index.js:53:10)
    at wget (/home/nodeuser/.nvm/versions/node/v10.13.0/lib/node_modules/node-wget/wget.js:46:4)
    at Object.<anonymous> (/home/nodeuser/.nvm/versions/node/v10.13.0/lib/node_modules/node-wget/cli.js:75:7)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
internal/streams/legacy.js:57
      throw er; // Unhandled stream error in pipe.
      ^

Error: EISDIR: illegal operation on a directory, open './estatic'
ERROR: null
Using Command: wget -q --recursive --timestamping --page-requisites --no-parent --no-host-directories --restrict-file-name=unix --trust-server-names --directory-prefix estatic http://localhost:2368/sitemap.xml
fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/tmp/estatic/sitemap.xml'
    at Object.openSync (fs.js:436:3)
    at Object.readFileSync (fs.js:341:35)
    at fetchUrlHelper (/home/nodeuser/.nvm/versions/node/v10.13.0/lib/node_modules/ghost-static-site-generator/src/helpers/fetchUrlHelper/fetchUrlHelper.js:32:29)
    at Array.forEach (<anonymous>)
    at mkdirp (/home/nodeuser/.nvm/versions/node/v10.13.0/lib/node_modules/ghost-static-site-generator/src/commands/generateStaticSite.js:34:12)
    at /home/nodeuser/.nvm/versions/node/v10.13.0/lib/node_modules/ghost-static-site-generator/node_modules/mkdirp/index.js:48:26
    at FSReqWrap.oncomplete (fs.js:155:5)
```

**Comment by Fried-Chicken** [comment]
@RobertoMalatesta Maybe try this `gssg --domain "http://localhost:2368" --url "http://localhost:8080" --subDir static --ignore-absolute-paths` and see if there are any errors.

**Comment by Fried-Chicken** [comment]
@RobertoMalatesta Maybe you can fork the repo and have a go at fixing it. Then raise a PR back into the repo. Since I don't have access to your environment, it's quite hard to trouble shoot it.

**Comment by RobertoMalatesta** [comment]
Already forked.
Just had a look around the code but I don't have time to spend on it.
Besides, **httrack** fits my needs at the moment.
Take care.

--R

**Comment by Fried-Chicken** [comment]
@RobertoMalatesta Oh that's unfortunate.
Glad you found something that fits your needs. You take care too.

@Fried-Chicken

**Comment by RobertoMalatesta** [comment]
One last thing that can be of help:
the regression is produced by the wget cmd line:
This does not work (as seen in the source):
` wget -q --recursive --timestamping --page-requisites --no-parent --no-host-directories --restrict-file-name=unix --trust-server-names --directory-prefix static http://localhost:2368/sitemap.xsl`
This works (without `--directory-prefix static `):
`wget -q --recursive --timestamping --page-requisites --no-parent --no-host-directories --restrict-file-name=unix --trust-server-names  http://localhost:2368/sitemap.xml`



--R

**Comment by Fried-Chicken** [comment]
@RobertoMalatesta Thanks for that, I'll have a look into it.

**Comment by RobertoMalatesta** [comment]
@Fried-Chicken don't.
I just saw that the possible culprit is me installing **node-wget** a couple of days ago.
That nifty package took over the path of regular **wget** but it's not 100% compatible.
I won't be touching that machine until Monday, but I assume that, once removed that package, that error will be gone. :smiling_imp:

**Comment by Fried-Chicken** [comment]
@RobertoMalatesta That's interesting please test and let me know. Also the latest version is `v1.0.0-2`

**Comment by Fried-Chicken** [comment]
@RobertoMalatesta That's great to hear. I'll be continuing to improve gssg so maybe when you use it. It'll be even better! :)
