### ISSUE TITLE
CSS and JS files not generating

### ISSUE THREAD

**Issue by aadimator** [Fried-Chicken/ghost-static-site-generator#14]
The `built` directory inside the assets is empty. No styling and JS functionality in the generated static site.

**Comment by Fried-Chicken** [comment]
Hey @aadimator Can you provide a bit more context? For example, what command did you use and also what theme are you using? Do you have custom styling injected?

**Comment by aadimator** [comment]
I used the command `gssg`
I'm using the default Casper theme but I've modified it a bit. I started the ghost blog on my local machine using the command `ghost start`.

**Comment by Fried-Chicken** [comment]
Hey @aadimator Is this the site `https://aadimator.com/` you are trying to product a static site for?

**Comment by aadimator** [comment]
No, I was trying to use the local installation at that time. It had the same setup as `https://aadimator.com/` , same theme and content etc. Now, I've also tried to generate the static site using `https://aadimator.com/` and it's not working for that as well.

**Comment by aadimator** [comment]
Ok, now I think I know what the problem was. It's not picking up the asset files relative to the directory. I was opening up `index.html` to preview the generated content. It's looking for the css and js files in a different directory. ![image](https://user-images.githubusercontent.com/10383542/51969990-9a5da200-2497-11e9-88cf-3553c76df64f.png)

**Comment by aadimator** [comment]
I've tried running this command as well: `gssg --domain https://aadimator.com --preview` but it fails with the following error.
![image](https://user-images.githubusercontent.com/10383542/51970324-7353a000-2498-11e9-9240-a9f732336688.png)

**Comment by Fried-Chicken** [comment]
@aadimator It looks like you need to install http-server. Since you are using Windows I'm not sure if it will work.

**Comment by Fried-Chicken** [comment]
Closing due to OS issue.

**Comment by scambier** [comment]
@Fried-Chicken 

There are two issues here:
- The initial problem (missing css and js files in the built folder)
- The crash of http-server when using --preview

I doubt that the two are related. I'm on Windows and have the same problems. However, I can use http-server independently.

When using `gssg` and looking at wget logs, I don't see it fetch any .js or .css files

**Comment by jon241** [comment]
This issue needs reopening as I am also getting this issue but no idea why.
