### ISSUE TITLE
Localhost not replaced in sitemap.xsl link

### ISSUE THREAD

**Issue by gottlike** [Fried-Chicken/ghost-static-site-generator#15]
The website's Domain/URL is not inserted in the link to the sitemap*.xsl files inside the sitemap*.xml files, e.g.:

```xml
<?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="//localhost:2368/sitemap.xsl"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" xmlns:image="http://www.google.com/schemas/sitemap-image/1.1"></urlset>
```

**Comment by Fried-Chicken** [comment]
Hey @gottlike 

Can you tell me which command you're using?

Thanks

**Comment by gottlike** [comment]
Hey. Sure, it's `gssg --url https://mydomain.ch --dest ../static`

**Comment by Fried-Chicken** [comment]
Hey @gottlike, Just published a new version for you. Try version `v1.0.1-0`

**Comment by gottlike** [comment]
It works now - thanks for the quick fix!

**Comment by Fried-Chicken** [comment]
@gottlike No worries. My pleasure :)
