### ISSUE TITLE
--url appends {{asset}} with 'v=6bbed80a06'

### ISSUE THREAD

**Issue by andyhstokes** [Fried-Chicken/ghost-static-site-generator#16]
When I run
`gssg --domain "http://localhost:2368" --url "myrepo.github.io" static --ignore-absolute-paths --preview`

The preview on localhost:8083 works perfectly, however the static files themselves have broken paths for anything linked via the {{asset}} helper.
**Static code:**
`<link rel="stylesheet" href="/assets/css/styles.css?v=6bbed80a06" />`

**Original ghost theme code:**
`<link rel="stylesheet" href="{{asset "css/styles.css"}}" />`

So the Asset helper is being appended with
> ?v=6bbed80a06

_osx 10.12_

**Comment by Fried-Chicken** [comment]
Hey @andyhstokes 

The `?v=6bbed80a06` shouldn't be an issue, that's just a query param. Can you try this command.
`gssg --domain "http://localhost:2368" --url "https://myrepo.github.io"` and let me know if it helps.

Thanks ☺️

@Fried-Chicken

**Comment by andyhstokes** [comment]
Hey. I fixed the problem I was having by removing the static folder and rerunning the command. I must have made a mistake in terminal and was just looking for errors (I'm not that adept at web design).

Thanks for the help and great work on the repo! I was looking to move away from my web host and found this via the comments on Buster.

**Comment by Fried-Chicken** [comment]
Hey @andyhstokes 

That's great to hear that you fixed it. Don't worry, practise makes perfect.
If you need any help, just give me a shout.

Hope you enjoy using my plugin!

@Fried-Chicken
