### ISSUE TITLE
Missing resized GIFs

### ISSUE THREAD

**Issue by LDubya** [Fried-Chicken/ghost-static-site-generator#27]
Hi, there seems to be a case where images are missing, due to not being resized by Ghost. This is specifically for animated gifs. When the theme requests a resized image and that image is an animated GIF, Ghost will just serve the original image instead of a resized one. It doesn't save a resized GIF in any size folder, it just serves the original image from the server. This is leading to missing resized GIF images. Are you just not giving the script enough time for Ghost to serve the image? How do we fix this?

_Originally posted by @LDubya in https://github.com/Fried-Chicken/ghost-static-site-generator/issues/8#issuecomment-536044051_

**Comment by ericalli** [comment]
@LDubya Did you happen to come across a solution to this issue? I'm still seeing it happen on my end.

**Comment by LDubya** [comment]
@ericalli unfortunately not. The “solution” for me was pasting the GIF into every folder where it should have been in.

**Comment by Fried-Chicken** [comment]
@LDubya Can you copy and paste some of the underlying html so I can see how the gif and images are loaded for you.

**Comment by LDubya** [comment]
Hey Mo, I stopped using this extension, but essentially, but for ghost static site generator, every image is auto-generated by Ghost at different file dimensions based on your theme code, etc, and then ghost static site generator uploads those images to their appropriate folders inside static content folders, based on their original image routes (in my case, first by year, then by dimensions). Your theme code decides which folders your images ultimately exist in, since your theme code is what instructs ghost to load images at different dimensions, and ghost will do that resizing. However, GIFs weren't being loaded by this process. I'm not sure of the underlying cause -- it may have been either a race condition or some other issue that prevented the GIFs from being loaded. So I basically had to manually do Ghost SSG's process and move every gif I needed into their appropriate static content folders.

**Comment by Fried-Chicken** [comment]
Thanks @LDubya for your reply, I will look into this, but for now I will close this ticket.
