### ISSUE TITLE
ERROR: null when running gssg

### ISSUE THREAD

**Issue by electriquo** [Fried-Chicken/ghost-static-site-generator#38]
thank for maintaining this package!

these are the versions i am using:

- gssg 1.0.1
- ghost 3.42.0
- ghost cli 1.16.0

when i execute gssg, it fails with `ERROR: null`.

```shell
$ ghost --version
Ghost-CLI version: 1.16.0
Ghost version: 3.42.0 (at /var/lib/ghost)

$ gssg --url https://mydomain.com --fail-on-error --silent
Fetching: http://localhost:2368/sitemap.xsl
Fetching: http://localhost:2368/sitemap.xml
Fetching: http://localhost:2368/sitemap-pages.xml
Fetching: http://localhost:2368/
ERROR: null
Using Command: wget -q --recursive --timestamping --page-requisites --no-parent --no-host-directories --restrict-file-name=unix --trust-server-names --directory-prefix static --content-on-error http://localhost:2368/
```

any clue what is wrong?

**Comment by zaksquatch** [comment]
I'm running into the same situation. 

Ghost-CLI version: 1.17.3
Ghost version: 4.6.4 (at C:\wamp64\www\ghost)
GSSG version: 1.0.1

**Comment by VimalMollyn** [comment]
Same issue!

**Comment by Fried-Chicken** [comment]
Hey Guys,

I've just released a new version, `v1.1.2` can you try that version and see if you still have any issues.

Thanks

**Comment by foolioo** [comment]
> I've just released a new version, `v1.1.4` can you try that version and see if you still have any issues.

@Fried-Chicken issue still happens

**Comment by dominioncfg** [comment]
The same thing was happening to me on Windows even though I have all the tools properly installed, On Linux seems to work (using WSL2).

**Comment by ItsIgnacioPortal** [comment]
I've fixed this bug in my fork of ghost-static-site-generator! https://github.com/itsignacioportal/ghost-static-site-generator/
