### ISSUE TITLE
Built folder is empty

### ISSUE THREAD

**Issue by SivertGullbergHansen** [Fried-Chicken/ghost-static-site-generator#68]
Hi, this issue has been brought up earlier but it has been closed and not re-opened for some reason, so I am creating a new one specifically for this issue:
![image](https://user-images.githubusercontent.com/6785315/188439891-cc528e9f-07f7-47af-843f-8769feed9daa.png)

My builds-folder is empty, thus no JS or CSS is loaded into the static site.

**Comment by ItsIgnacioPortal** [comment]
I've fixed this bug in my fork of ghost-static-site-generator! https://github.com/itsignacioportal/ghost-static-site-generator/

**Comment by cggaurav** [comment]
Same issue! Thanks for fixing @ItsIgnacioPortal, could we merge above ^ @Fried-Chicken ?
