### ISSUE TITLE
Async fetching would speed things up

### ISSUE THREAD

**Issue by Stono** [Fried-Chicken/ghost-static-site-generator#9]
At the moment everything is done sync, spawning from https://github.com/Fried-Chicken/ghost-static-site-generator/blob/master/src/commands/generateStaticSite.js#L32

Having some parallelism would speed things up drastically, 10 or 20 simultaneous requests for example.

A library such as https://www.npmjs.com/package/run-parallel-limit could help with that.

**Comment by Fried-Chicken** [comment]
I need to look at how to do this, it's currently synchronous because I need to wait for all the files to download before removing query strings, and replacing urls. Any ideas?

**Comment by Fried-Chicken** [comment]
I've made the fetching of responsive images async, this speeds up the download, but  haven't been able to make the crawling of the site async as we need to have all html files downloaded before we run some mods on them. This would require some extensive work. Not a quick win in my opinion.

**Comment by Fried-Chicken** [comment]
Hi @Stono

I'm closing this ticket, please re-open if it's still valid for you.

Thanks

@Fried-Chicken
